# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: armagankaratosun@gmail.com
author_name: Armagan Karatosun
create_claude_symlink: true
create_gemini_symlink: true
has_ai_rules: true
has_binder: false
has_settings: true
kind: frontend-and-server
labextension_name: jupyterlab-kubeflow-pipelines
project_short_description: Kubeflow Pipelines v2 integration for JupyterLab.
python_name: jupyterlab_kubeflow_pipelines
repository: https://github.com/armagankaratosun/jupyterlab-kubeflow-pipelines
test: true

