from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class DagPreview:
    mermaid: str


def _safe_mermaid_id(value: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in value) or "node"


def _mermaid_escape_label(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build_dag_preview(pipeline_func: Any) -> DagPreview:
    """
    Build a Mermaid DAG preview from a KFP v2 pipeline function.

    This uses the in-memory `pipeline_spec` generated by the KFP DSL.
    """
    pipeline_spec = getattr(pipeline_func, "pipeline_spec", None)
    if pipeline_spec is None:
        raise TypeError(
            "Expected a @dsl.pipeline function (GraphComponent) with pipeline_spec."
        )

    root = getattr(pipeline_spec, "root", None)
    dag = getattr(root, "dag", None) if root is not None else None
    tasks = getattr(dag, "tasks", None) if dag is not None else None
    if tasks is None:
        raise ValueError("Pipeline spec has no root.dag.tasks to render.")

    lines: list[str] = ["graph TD"]

    for task_name, task in tasks.items():
        node_id = _safe_mermaid_id(task_name)
        task_info = getattr(task, "task_info", None)
        label = getattr(task_info, "name", None) if task_info is not None else None
        label = label or task_name

        component_ref = getattr(task, "component_ref", None)
        component_name = (
            getattr(component_ref, "name", None) if component_ref is not None else None
        )
        if component_name:
            display = f"{label}\\n({component_name})"
        else:
            display = label

        lines.append(f'  {node_id}["{_mermaid_escape_label(display)}"]')

    for task_name, task in tasks.items():
        node_id = _safe_mermaid_id(task_name)
        dependent_tasks = getattr(task, "dependent_tasks", None) or []
        for dep in dependent_tasks:
            lines.append(f"  {_safe_mermaid_id(dep)} --> {node_id}")

    return DagPreview(mermaid="\n".join(lines) + "\n")


def display_dag_preview(pipeline_func: Any, *, title: str | None = None) -> None:
    """
    Render a pipeline DAG preview inside a notebook cell.

    Emits a custom mimetype that the JupyterLab extension can render using the
    bundled Mermaid dependency.
    """
    preview = build_dag_preview(pipeline_func)

    try:
        from IPython.display import display
    except ImportError:
        raise RuntimeError(
            "IPython is required to display a DAG preview in a notebook."
        )

    mime = "application/vnd.jupyterlab-kubeflow-pipelines.mermaid+json"
    payload = {"title": title, "mermaid": preview.mermaid}
    display({mime: payload, "text/plain": preview.mermaid}, raw=True)
